const productTypes = [
  {
    product_type: 4,
    product_name: "AG",
    prefix: "26a",
    suffix: "",
    remark: "",
  },
  {
    product_type: 79,
    product_name: "BB",
    prefix: "26a",
    suffix: "",
    remark: "",
  },
  {
    product_type: 41,
    product_name: "BG",
    prefix: "26a",
    suffix: "",
    remark: "",
  },
  {
    product_type: 221,
    product_name: "BOLE",
    prefix: "26a",
    suffix: "",
    remark: "",
  },
  {
    product_type: 16,
    product_name: "CQ9",
    prefix: "26a",
    suffix: "",
    remark: "",
  },
  {
    product_type: 65,
    product_name: "CR",
    prefix: "26a",
    suffix: "",
    remark: "",
  },
  {
    product_type: 141,
    product_name: "FC",
    prefix: "26a",
    suffix: "",
    remark: "",
  },
  {
    product_type: 55,
    product_name: "JDB",
    prefix: "26a",
    suffix: "",
    remark: "",
  },
  {
    product_type: 38,
    product_name: "KY",
    prefix: "26a",
    suffix: "",
    remark: "",
  },
  {
    product_type: 143,
    product_name: "LY",
    prefix: "26a",
    suffix: "",
    remark: "",
  },
  {
    product_type: 6,
    product_name: "MGS",
    prefix: "26a",
    suffix: "",
    remark: "",
  },
  {
    product_type: 98,
    product_name: "PG",
    prefix: "26a",
    suffix: "",
    remark: "",
  },
  {
    product_type: 2,
    product_name: "TCG ELOTTO",
    prefix: "无",
    suffix: "",
    remark: "",
  },
  {
    product_type: 99,
    product_name: "TF",
    prefix: "26a",
    suffix: "",
    remark: "",
  },
  {
    product_type: 73,
    product_name: "VR",
    prefix: "26a",
    suffix: "",
    remark: "",
  },
  {
    product_type: 152,
    product_name: "WL",
    prefix: "26a",
    suffix: "",
    remark: "",
  },
];

export default productTypes;
